# Generated by Django 5.2.2 on 2025-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_dish_rice',
            name='restaurant_area',
            field=models.CharField(choices=[('Hong Kong', 'Hong Kong'), ('Kowloon', 'Kowloon'), ('New Territories', 'New Territories'), ('Islands', 'Islands')], max_length=50),
        ),
        migrations.AlterField(
            model_name='two_dish_rice',
            name='restaurant_district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tuen Mun', 'Tuen Mun'), ('Tsuen Wan', 'Tsuen Wan'), ('Yuen Long', 'Yuen Long'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wang Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], max_length=50),
        ),
    ]
