# Generated by Django 5.2.3 on 2025-06-17 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodieInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='foodie_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foodie_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('1', '10-20'), ('2', '21-30'), ('3', '31-40'), ('4', '41-50'), ('5', '51-60'), ('6', '61-70'), ('7', '71-80'), ('8', 'Over 80')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('white_collar', '白領'), ('technician', '技工'), ('driver', '司機'), ('housewife', '主婦'), ('boss', '老闆'), ('other', '其他')], max_length=50, null=True)),
                ('live_district', models.CharField(blank=True, choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tuen Mun', 'Tuen Mun'), ('Tsuen Wan', 'Tsuen Wan'), ('Yuen Long', 'Yuen Long'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], max_length=50, null=True)),
                ('favor_chinese', models.BooleanField(default=False)),
                ('favor_western', models.BooleanField(default=False)),
                ('favor_veg', models.BooleanField(default=False)),
                ('favor_organic', models.BooleanField(default=False)),
                ('favor_japan', models.BooleanField(default=False)),
                ('favor_korean', models.BooleanField(default=False)),
                ('favor_thai', models.BooleanField(default=False)),
                ('favor_seafood', models.BooleanField(default=False)),
                ('favor_muslim', models.BooleanField(default=False)),
                ('favor_no_beef', models.BooleanField(default=False)),
                ('favor_no_pork', models.BooleanField(default=False)),
                ('foodie_desc', models.TextField(blank=True)),
                ('foodie_photo', models.ImageField(blank=True, null=True, upload_to='photos/foodie/%Y/%m/%d/')),
                ('is_mvp', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foodie Profile',
                'verbose_name_plural': 'Foodie Profiles',
            },
        ),
    ]
