# Generated by Django 5.2.3 on 2025-06-20 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodie_name', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age_range', models.CharField(choices=[('1', '10-20'), ('2', '21-30'), ('3', '31-40'), ('4', '41-50'), ('5', '51-60'), ('6', '61-70'), ('7', '71-80'), ('8', 'over 80')], max_length=10)),
                ('occupation', models.CharField(choices=[('office', '白領'), ('technical', '技工'), ('driver', '司機'), ('wife', '主婦'), ('boss', '老闆'), ('other', '其他')], max_length=20)),
                ('live_district', models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], max_length=50)),
                ('favor_chinese', models.BooleanField(default=False)),
                ('favor_western', models.BooleanField(default=False)),
                ('favor_veg', models.BooleanField(default=False)),
                ('favor_organic', models.BooleanField(default=False)),
                ('favor_japan', models.BooleanField(default=False)),
                ('favor_korean', models.BooleanField(default=False)),
                ('favor_thai', models.BooleanField(default=False)),
                ('favor_seafood', models.BooleanField(default=False)),
                ('favor_muslim', models.BooleanField(default=False)),
                ('favor_no_beef', models.BooleanField(default=False)),
                ('favor_no_pork', models.BooleanField(default=False)),
                ('foodie_desc', models.CharField(max_length=200)),
                ('foodie_photo', models.ImageField(blank=True, upload_to='foodie_photos/')),
                ('is_mvp', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodieInfo',
        ),
    ]
